//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
        "tract")]
    public partial class FileReconcilationMessage
    {
        
        private string agencyUniqueCodeField;
        
        private string clientIPField;
        
        private System.Xml.XmlElement getAgencyDetailsDataField;
        
        private System.Xml.XmlElement getDataForBenResField;
        
        private System.Xml.XmlElement getDataForCrdtSttsResField;
        
        private object[] getDataForSttsRptResponseField;
        
        private string messageIdField;
        
        private string passwordField;
        
        private string recordCountField;
        
        private string schemeCodeField;
        
        private string sourceCodeField;
        
        private string usernameField;
        
        private int oResultForMessageValidationField;
        
        private bool oResultForMessageValidationFieldSpecified;
        
        private FileDetailsParams1 objFileDetailsParamsField;
        
        private xmlSoapBody1 oxmlsoapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AgencyUniqueCode
        {
            get
            {
                return this.agencyUniqueCodeField;
            }
            set
            {
                this.agencyUniqueCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ClientIP
        {
            get
            {
                return this.clientIPField;
            }
            set
            {
                this.clientIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Xml.XmlElement GetAgencyDetailsData
        {
            get
            {
                return this.getAgencyDetailsDataField;
            }
            set
            {
                this.getAgencyDetailsDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Xml.XmlElement GetDataForBenRes
        {
            get
            {
                return this.getDataForBenResField;
            }
            set
            {
                this.getDataForBenResField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Xml.XmlElement GetDataForCrdtSttsRes
        {
            get
            {
                return this.getDataForCrdtSttsResField;
            }
            set
            {
                this.getDataForCrdtSttsResField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] GetDataForSttsRptResponse
        {
            get
            {
                return this.getDataForSttsRptResponseField;
            }
            set
            {
                this.getDataForSttsRptResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string RecordCount
        {
            get
            {
                return this.recordCountField;
            }
            set
            {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string SchemeCode
        {
            get
            {
                return this.schemeCodeField;
            }
            set
            {
                this.schemeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string SourceCode
        {
            get
            {
                return this.sourceCodeField;
            }
            set
            {
                this.sourceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int oResultForMessageValidation
        {
            get
            {
                return this.oResultForMessageValidationField;
            }
            set
            {
                this.oResultForMessageValidationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oResultForMessageValidationSpecified
        {
            get
            {
                return this.oResultForMessageValidationFieldSpecified;
            }
            set
            {
                this.oResultForMessageValidationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public FileDetailsParams1 objFileDetailsParams
        {
            get
            {
                return this.objFileDetailsParamsField;
            }
            set
            {
                this.objFileDetailsParamsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public xmlSoapBody1 oxmlsoap
        {
            get
            {
                return this.oxmlsoapField;
            }
            set
            {
                this.oxmlsoapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
        "tract")]
    public partial class FileReconcilationMessage_PFMS_CrdtSttsResponse
    {
        
        private string bankcodeField;
        
        private object[] getDataField;
        
        private string passwordField;
        
        private System.Xml.XmlElement responseMessageField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Bankcode
        {
            get
            {
                return this.bankcodeField;
            }
            set
            {
                this.bankcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] GetData
        {
            get
            {
                return this.getDataField;
            }
            set
            {
                this.getDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Xml.XmlElement ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="xmlSoapBody", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
        "tract")]
    public partial class xmlSoapBody1
    {
        
        private string errorCodeField;
        
        private string errorValueField;
        
        private System.Xml.XmlElement xmlELeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorValue
        {
            get
            {
                return this.errorValueField;
            }
            set
            {
                this.errorValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Xml.XmlElement xmlELe
        {
            get
            {
                return this.xmlELeField;
            }
            set
            {
                this.xmlELeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="FileDetailsParams", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
        "tract")]
    public partial class FileDetailsParams1
    {
        
        private string fileTypeField;
        
        private System.DateTime fromDateField;
        
        private bool fromDateFieldSpecified;
        
        private string sourceField;
        
        private System.DateTime todateField;
        
        private bool todateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime FromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromDateSpecified
        {
            get
            {
                return this.fromDateFieldSpecified;
            }
            set
            {
                this.fromDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Todate
        {
            get
            {
                return this.todateField;
            }
            set
            {
                this.todateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TodateSpecified
        {
            get
            {
                return this.todateFieldSpecified;
            }
            set
            {
                this.todateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileReconcilationMessage_GetAgencyDetails
    {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlElement getAgencyDetailsDataField;
        
        private System.Xml.XmlElement responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement GetAgencyDetailsData
        {
            get
            {
                return this.getAgencyDetailsDataField;
            }
            set
            {
                this.getAgencyDetailsDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Xml.XmlElement ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class xmlSoapBody
    {
        
        private System.Xml.XmlElement xmlELeField;
        
        private string errorCodeField;
        
        private string errorValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Xml.XmlElement xmlELe
        {
            get
            {
                return this.xmlELeField;
            }
            set
            {
                this.xmlELeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorValue
        {
            get
            {
                return this.errorValueField;
            }
            set
            {
                this.errorValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileDetailsParams
    {
        
        private string sourceField;
        
        private System.DateTime fromDateField;
        
        private System.DateTime todateField;
        
        private string fileTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime FromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Todate
        {
            get
            {
                return this.todateField;
            }
            set
            {
                this.todateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankService.IFileReconcilationContract")]
    internal interface IFileReconcilationContract
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_FileDetails", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_FileDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_FileDetailsFileReconcilationMe" +
            "ssageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage1> PFMS_FileDetailsAsync(BankService.FileReconcilationMessage1 request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_MarkFilesReqfromPFMS", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_MarkFilesReqfromPFMSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_MarkFilesReqfromPFMSFileReconc" +
            "ilationMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage1> PFMS_MarkFilesReqfromPFMSAsync(BankService.FileReconcilationMessage1 request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_SendSingleFile", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_SendSingleFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_SendSingleFileFileReconcilatio" +
            "nMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage1> PFMS_SendSingleFileAsync(BankService.FileReconcilationMessage1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetAgencyDetails", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_GetAgencyDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetAgencyDetailsFileReconcilat" +
            "ionMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetAgencyDetails> PFMS_GetAgencyDetailsAsync(BankService.FileReconcilationMessage_GetAgencyDetails oSoapEnvelop);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_BenResponse", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_BenResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_BenResponseFileReconcilationMe" +
            "ssageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationResponseMessage> PFMS_BenResponseAsync(BankService.FileReconcilationMessage1 request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_CrdtSttsResponse", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_CrdtSttsResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage_PFMS_CrdtSttsResponse), Action="http://tempuri.org/IFileReconcilationContract/PFMS_CrdtSttsResponseFileReconcilat" +
            "ionMessage_PFMS_CrdtSttsResponseFault", Name="FileReconcilationMessage_PFMS_CrdtSttsResponse", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_PFMS_CrdtSttsResponse1> PFMS_CrdtSttsResponseAsync(BankService.FileReconcilationMessage_PFMS_CrdtSttsResponse1 request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_SttsRptResponse", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_SttsRptResponseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_SttsRptResponseFileReconcilati" +
            "onMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_SttsRptResponse> PFMS_SttsRptResponseAsync(BankService.FileReconcilationMessage_SttsRptResponse request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetAllAgencyInfo", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_GetAllAgencyInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetAllAgencyInfoFileReconcilat" +
            "ionMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetAllAgencyInfo> PFMS_GetAllAgencyInfoAsync(BankService.FileReconcilationMessage_GetAllAgencyInfo request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetBankBranchByIFSC", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_GetBankBranchByIFSCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetBankBranchByIFSCFileReconci" +
            "lationMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetBankBranchByIFSC> PFMS_GetBankBranchByIFSCAsync(BankService.FileReconcilationMessage_GetBankBranchByIFSC request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_AgencyRemainingBalance", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_AgencyRemainingBalanceResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_AgencyRemainingBalanceFileReco" +
            "ncilationMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_Common> PFMS_AgencyRemainingBalanceAsync(BankService.FileReconcilationMessage_Common request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_AgencyUserDetails", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_AgencyUserDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_AgencyUserDetailsFileReconcila" +
            "tionMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_Common> PFMS_AgencyUserDetailsAsync(BankService.FileReconcilationMessage_Common request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetBankDetailByDate", ReplyAction="http://tempuri.org/IFileReconcilationContract/PFMS_GetBankDetailByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BankService.FileReconcilationMessage), Action="http://tempuri.org/IFileReconcilationContract/PFMS_GetBankDetailByDateFileReconci" +
            "lationMessageFault", Name="FileReconcilationMessage", Namespace="http://schemas.datacontract.org/2004/07/CGA.CPSMS.WebService.Contracts.MessageCon" +
            "tract")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_PFMS_CrdtSttsResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileReconcilationMessage_GetAgencyDetails))]
        System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetBankDetail> PFMS_GetBankDetailByDateAsync(BankService.FileReconcilationMessage_GetBankDetail request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationMessage1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AgencyUniqueCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ClientIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Xml.XmlElement GetAgencyDetailsData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Xml.XmlElement GetDataForBenRes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Xml.XmlElement GetDataForCrdtSttsRes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Xml.XmlNode GetDataForSttsRptResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string MessageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string RecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string SchemeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string SourceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public int oResultForMessageValidation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public BankService.FileDetailsParams objFileDetailsParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public BankService.xmlSoapBody oxmlsoap;
        
        public FileReconcilationMessage1()
        {
        }
        
        public FileReconcilationMessage1(string Password, string Username, string AgencyUniqueCode, string ClientIP, System.Xml.XmlElement GetAgencyDetailsData, System.Xml.XmlElement GetDataForBenRes, System.Xml.XmlElement GetDataForCrdtSttsRes, System.Xml.XmlNode GetDataForSttsRptResponse, string MessageId, string RecordCount, string SchemeCode, string SourceCode, int oResultForMessageValidation, BankService.FileDetailsParams objFileDetailsParams, BankService.xmlSoapBody oxmlsoap)
        {
            this.Password = Password;
            this.Username = Username;
            this.AgencyUniqueCode = AgencyUniqueCode;
            this.ClientIP = ClientIP;
            this.GetAgencyDetailsData = GetAgencyDetailsData;
            this.GetDataForBenRes = GetDataForBenRes;
            this.GetDataForCrdtSttsRes = GetDataForCrdtSttsRes;
            this.GetDataForSttsRptResponse = GetDataForSttsRptResponse;
            this.MessageId = MessageId;
            this.RecordCount = RecordCount;
            this.SchemeCode = SchemeCode;
            this.SourceCode = SourceCode;
            this.oResultForMessageValidation = oResultForMessageValidation;
            this.objFileDetailsParams = objFileDetailsParams;
            this.oxmlsoap = oxmlsoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationResponseMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ClientIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Xml.XmlElement ResponseMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public BankService.FileDetailsParams objFileDetailsParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public BankService.xmlSoapBody oxmlsoap;
        
        public FileReconcilationResponseMessage()
        {
        }
        
        public FileReconcilationResponseMessage(string Password, string Username, string ClientIP, System.Xml.XmlElement ResponseMessage, BankService.FileDetailsParams objFileDetailsParams, BankService.xmlSoapBody oxmlsoap)
        {
            this.Password = Password;
            this.Username = Username;
            this.ClientIP = ClientIP;
            this.ResponseMessage = ResponseMessage;
            this.objFileDetailsParams = objFileDetailsParams;
            this.oxmlsoap = oxmlsoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationMessage_PFMS_CrdtSttsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationMessage_PFMS_CrdtSttsResponse1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Bankcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Xml.XmlNode GetData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Xml.XmlElement ResponseMessage;
        
        public FileReconcilationMessage_PFMS_CrdtSttsResponse1()
        {
        }
        
        public FileReconcilationMessage_PFMS_CrdtSttsResponse1(string Password, string Username, string Bankcode, System.Xml.XmlNode GetData, System.Xml.XmlElement ResponseMessage)
        {
            this.Password = Password;
            this.Username = Username;
            this.Bankcode = Bankcode;
            this.GetData = GetData;
            this.ResponseMessage = ResponseMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationMessage_SttsRptResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationMessage_SttsRptResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlNode GetData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Xml.XmlElement ResponseMessage;
        
        public FileReconcilationMessage_SttsRptResponse()
        {
        }
        
        public FileReconcilationMessage_SttsRptResponse(string Password, string Username, System.Xml.XmlNode GetData, System.Xml.XmlElement ResponseMessage)
        {
            this.Password = Password;
            this.Username = Username;
            this.GetData = GetData;
            this.ResponseMessage = ResponseMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationMessage_GetAllAgencyInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationMessage_GetAllAgencyInfo
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DistrictCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Xml.XmlElement GetAllAgencyInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SchemeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string StateCode;
        
        public FileReconcilationMessage_GetAllAgencyInfo()
        {
        }
        
        public FileReconcilationMessage_GetAllAgencyInfo(string Password, string Username, string DistrictCode, System.Xml.XmlElement GetAllAgencyInfo, string SchemeCode, string StateCode)
        {
            this.Password = Password;
            this.Username = Username;
            this.DistrictCode = DistrictCode;
            this.GetAllAgencyInfo = GetAllAgencyInfo;
            this.SchemeCode = SchemeCode;
            this.StateCode = StateCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationMessage_GetBankBranchByIFSC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationMessage_GetBankBranchByIFSC
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlElement GetData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Xml.XmlElement ResponseMessage;
        
        public FileReconcilationMessage_GetBankBranchByIFSC()
        {
        }
        
        public FileReconcilationMessage_GetBankBranchByIFSC(string Password, string Username, System.Xml.XmlElement GetData, System.Xml.XmlElement ResponseMessage)
        {
            this.Password = Password;
            this.Username = Username;
            this.GetData = GetData;
            this.ResponseMessage = ResponseMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationMessage_Common", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationMessage_Common
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlElement GetData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Xml.XmlElement ResponseMessage;
        
        public FileReconcilationMessage_Common()
        {
        }
        
        public FileReconcilationMessage_Common(string Password, string Username, System.Xml.XmlElement GetData, System.Xml.XmlElement ResponseMessage)
        {
            this.Password = Password;
            this.Username = Username;
            this.GetData = GetData;
            this.ResponseMessage = ResponseMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReconcilationMessage_GetBankDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    internal partial class FileReconcilationMessage_GetBankDetail
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlElement GetData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Xml.XmlElement ResponseMessage;
        
        public FileReconcilationMessage_GetBankDetail()
        {
        }
        
        public FileReconcilationMessage_GetBankDetail(string Password, string Username, System.Xml.XmlElement GetData, System.Xml.XmlElement ResponseMessage)
        {
            this.Password = Password;
            this.Username = Username;
            this.GetData = GetData;
            this.ResponseMessage = ResponseMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface IFileReconcilationContractChannel : BankService.IFileReconcilationContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class FileReconcilationContractClient : System.ServiceModel.ClientBase<BankService.IFileReconcilationContract>, BankService.IFileReconcilationContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FileReconcilationContractClient() : 
                base(FileReconcilationContractClient.GetDefaultBinding(), FileReconcilationContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IFileReconcilationContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReconcilationContractClient(EndpointConfiguration endpointConfiguration) : 
                base(FileReconcilationContractClient.GetBindingForEndpoint(endpointConfiguration), FileReconcilationContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReconcilationContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FileReconcilationContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReconcilationContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FileReconcilationContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileReconcilationContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage1> PFMS_FileDetailsAsync(BankService.FileReconcilationMessage1 request)
        {
            return base.Channel.PFMS_FileDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage1> PFMS_MarkFilesReqfromPFMSAsync(BankService.FileReconcilationMessage1 request)
        {
            return base.Channel.PFMS_MarkFilesReqfromPFMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage1> PFMS_SendSingleFileAsync(BankService.FileReconcilationMessage1 request)
        {
            return base.Channel.PFMS_SendSingleFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetAgencyDetails> PFMS_GetAgencyDetailsAsync(BankService.FileReconcilationMessage_GetAgencyDetails oSoapEnvelop)
        {
            return base.Channel.PFMS_GetAgencyDetailsAsync(oSoapEnvelop);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationResponseMessage> PFMS_BenResponseAsync(BankService.FileReconcilationMessage1 request)
        {
            return base.Channel.PFMS_BenResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_PFMS_CrdtSttsResponse1> PFMS_CrdtSttsResponseAsync(BankService.FileReconcilationMessage_PFMS_CrdtSttsResponse1 request)
        {
            return base.Channel.PFMS_CrdtSttsResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_SttsRptResponse> PFMS_SttsRptResponseAsync(BankService.FileReconcilationMessage_SttsRptResponse request)
        {
            return base.Channel.PFMS_SttsRptResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetAllAgencyInfo> PFMS_GetAllAgencyInfoAsync(BankService.FileReconcilationMessage_GetAllAgencyInfo request)
        {
            return base.Channel.PFMS_GetAllAgencyInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetBankBranchByIFSC> PFMS_GetBankBranchByIFSCAsync(BankService.FileReconcilationMessage_GetBankBranchByIFSC request)
        {
            return base.Channel.PFMS_GetBankBranchByIFSCAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_Common> PFMS_AgencyRemainingBalanceAsync(BankService.FileReconcilationMessage_Common request)
        {
            return base.Channel.PFMS_AgencyRemainingBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_Common> PFMS_AgencyUserDetailsAsync(BankService.FileReconcilationMessage_Common request)
        {
            return base.Channel.PFMS_AgencyUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankService.FileReconcilationMessage_GetBankDetail> PFMS_GetBankDetailByDateAsync(BankService.FileReconcilationMessage_GetBankDetail request)
        {
            return base.Channel.PFMS_GetBankDetailByDateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IFileReconcilationContract))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IFileReconcilationContract))
            {
                return new System.ServiceModel.EndpointAddress("https://pfms.nic.in/PFMSWebService/Service/FileReconcilationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FileReconcilationContractClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IFileReconcilationContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FileReconcilationContractClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IFileReconcilationContract);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IFileReconcilationContract,
        }
    }
}
